mq:
  channelName: NCTS.CLIENT.SVRCONN
  queueManager: RU.FTS.CITTU.RNTS.CLIENT
  queueDestinationName: RU.FTS.CITTU.RNTS.APP
  queueRecievedName: 10502060.INCOME
  port: 1415
  hostname: 31.186.98.2

# Details for our datasource
# Hibernate properties
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transit_service
    username: postgres
    password: 2150
  jpa:
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: false
