wmq:
  channelName: NCTS.CLIENT.SVRCONN
  queueManager: RU.FTS.CITTU.RNTS.CLIENT
  queueDestinationName: RU.FTS.CITTU.RNTS.APP
  queueRecievedName: 10502060.INCOME
  port: 1415
  hostname: 31.186.98.2

# Details for our datasource
# Hibernate properties
spring:
  datasource:
    url: jdbc:oracle:thin:@31.186.98.2:1521/ASKTT2_CLIENT
    username: TEST
    password: TEST
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: false
  jta:
    enabled: true
pool:
    size: 4

